import os
import requests
import fasttext
from tqdm import tqdm

LANGID_URL = "https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin"

def download(url, fname):
    resp = requests.get(url, stream=True)
    total = int(resp.headers.get('content-length', 0))
    with open(fname + "_part", 'wb') as file, tqdm(
        desc="Downloading langid model",
        total=total,
        unit='iB',
        unit_scale=True,
        unit_divisor=1024,
    ) as bar:
        for data in resp.iter_content(chunk_size=1024):
            size = file.write(data)
            bar.update(size)
    
    os.rename(fname + "_part", fname)

def load_langid_model(cache_dir=None):
    if not cache_dir:
        try:
            import torch
            from torch.hub import _get_torch_home
            torch_cache_home = _get_torch_home()
        except ImportError:
            torch_cache_home = os.path.expanduser(
                os.getenv(
                    'TORCH_HOME', 
                    os.path.join(os.getenv('XDG_CACHE_HOME', '~/.cache'), 'torch')
                )
            )

        cache_dir = os.path.join(torch_cache_home, 'fasttext')

    model_path = os.path.join(cache_dir, "lid.176.bin")
    if not os.path.isfile(model_path):
        os.makedirs(os.path.dirname(model_path), exist_ok=True)
        download(LANGID_URL, model_path)

    return fasttext.load_model(model_path)


LANG2ISO = {
    "oromo": "om",
    "french": "fr",
    "amharic": "am",
    "arabic": "ar",
    "azerbaijani": "az",
    "bengali": "bn",
    "burmese": "my",
    "chinese_simplified": "zh",
    "chinese_traditional": "zh",
    "welsh": "cy",
    "english": "en",
    "kirundi": "rn",
    "gujarati": "gu",
    "hausa": "ha",
    "hindi": "hi",
    "igbo": "ig",
    "indonesian": "id",
    "japanese": "ja",
    "korean": "ko",
    "kyrgyz": "ky",
    "marathi": "mr",
    "spanish": "es",
    "scottish_gaelic": "gd",
    "nepali": "np",
    "pashto": "ps",
    "persian": "fa",
    "pidgin": "pcm",
    "portuguese": "pt",
    "punjabi": "pa",
    "russian": "ru",
    "serbian_cyrillic": "sr",
    "serbian_latin": "sr",
    "sinhala": "si",
    "somali": "so",
    "swahili": "sw",
    "tamil": "ta",
    "telugu": "te",
    "thai": "th",
    "tigrinya": "ti",
    "turkish": "tr",
    "ukrainian": "uk",
    "urdu": "ur",
    "uzbek": "uz",
    "vietnamese": "vi",
    "yoruba": "yo"
}    

FASTTEXT_LANGS = set([
    "af",
    "als",
    "am",
    "an",
    "ar",
    "arz",
    "as",
    "ast",
    "av",
    "az",
    "azb",
    "ba",
    "bar",
    "bcl",
    "be",
    "bg",
    "bh",
    "bn",
    "bo",
    "bpy",
    "br",
    "bs",
    "bxr",
    "ca",
    "cbk",
    "ce",
    "ceb",
    "ckb",
    "co",
    "cs",
    "cv",
    "cy",
    "da",
    "de",
    "diq",
    "dsb",
    "dty",
    "dv",
    "el",
    "eml",
    "en",
    "eo",
    "es",
    "et",
    "eu",
    "fa",
    "fi",
    "fr",
    "frr",
    "fy",
    "ga",
    "gd",
    "gl",
    "gn",
    "gom",
    "gu",
    "gv",
    "he",
    "hi",
    "hif",
    "hr",
    "hsb",
    "ht",
    "hu",
    "hy",
    "ia",
    "id",
    "ie",
    "ilo",
    "io",
    "is",
    "it",
    "ja",
    "jbo",
    "jv",
    "ka",
    "kk",
    "km",
    "kn",
    "ko",
    "krc",
    "ku",
    "kv",
    "kw",
    "ky",
    "la",
    "lb",
    "lez",
    "li",
    "lmo",
    "lo",
    "lrc",
    "lt",
    "lv",
    "mai",
    "mg",
    "mhr",
    "min",
    "mk",
    "ml",
    "mn",
    "mr",
    "mrj",
    "ms",
    "mt",
    "mwl",
    "my",
    "myv",
    "mzn",
    "nah",
    "nap",
    "nds",
    "ne",
    "new",
    "nl",
    "nn",
    "no",
    "oc",
    "or",
    "os",
    "pa",
    "pam",
    "pfl",
    "pl",
    "pms",
    "pnb",
    "ps",
    "pt",
    "qu",
    "rm",
    "ro",
    "ru",
    "rue",
    "sa",
    "sah",
    "sc",
    "scn",
    "sco",
    "sd",
    "sh",
    "si",
    "sk",
    "sl",
    "so",
    "sq",
    "sr",
    "su",
    "sv",
    "sw",
    "ta",
    "te",
    "tg",
    "th",
    "tk",
    "tl",
    "tr",
    "tt",
    "tyv",
    "ug",
    "uk",
    "ur",
    "uz",
    "vec",
    "vep",
    "vi",
    "vls",
    "vo",
    "wa",
    "war",
    "wuu",
    "xal",
    "xmf",
    "yi",
    "yo",
    "yue",
    "zh"
])

